require("user.config")

require("user.options")
require("user.keymaps")
require("user.plugin-loader")

require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.bufferline")
require("user.toggleterm")
require("user.lualine")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
require("user.illuminate")
require("user.surround")

require("user.latex")
