return {
	alpha = {
		find_file = "",
		new_file = "",
		project = "",
		recent = "",
		find_text = "",
		setting = "",
		close = "",
	},
	nvimtree = {
		hint = "",
		info = "",
		warning = "",
		error = "",
    default = "",
    symlink = "",
    git = {
      unstaged = "",
      staged = "S",
      unmerged = "",
      renamed = "➜",
      deleted = "",
      untracked = "U",
      ignored = "◌",
    },
    folder = {
      default = "",
      open = "",
      empty = "",
      empty_open = "",
      symlink = "",
    },
	},
}
